(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(connection-local-criteria-alist
   '(((:application eshell)
      eshell-connection-default-profile)
     ((:application tramp)
      tramp-connection-local-default-system-profile tramp-connection-local-default-shell-profile)))
 '(connection-local-profile-alist
   '((eshell-connection-default-profile
      (eshell-path-env-list))
     (tramp-connection-local-darwin-ps-profile
      (tramp-process-attributes-ps-args "-acxww" "-o" "pid,uid,user,gid,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" "-o" "state=abcde" "-o" "ppid,pgid,sess,tty,tpgid,minflt,majflt,time,pri,nice,vsz,rss,etime,pcpu,pmem,args")
      (tramp-process-attributes-ps-format
       (pid . number)
       (euid . number)
       (user . string)
       (egid . number)
       (comm . 52)
       (state . 5)
       (ppid . number)
       (pgrp . number)
       (sess . number)
       (ttname . string)
       (tpgid . number)
       (minflt . number)
       (majflt . number)
       (time . tramp-ps-time)
       (pri . number)
       (nice . number)
       (vsize . number)
       (rss . number)
       (etime . tramp-ps-time)
       (pcpu . number)
       (pmem . number)
       (args)))
     (tramp-connection-local-busybox-ps-profile
      (tramp-process-attributes-ps-args "-o" "pid,user,group,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" "-o" "stat=abcde" "-o" "ppid,pgid,tty,time,nice,etime,args")
      (tramp-process-attributes-ps-format
       (pid . number)
       (user . string)
       (group . string)
       (comm . 52)
       (state . 5)
       (ppid . number)
       (pgrp . number)
       (ttname . string)
       (time . tramp-ps-time)
       (nice . number)
       (etime . tramp-ps-time)
       (args)))
     (tramp-connection-local-bsd-ps-profile
      (tramp-process-attributes-ps-args "-acxww" "-o" "pid,euid,user,egid,egroup,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" "-o" "state,ppid,pgid,sid,tty,tpgid,minflt,majflt,time,pri,nice,vsz,rss,etimes,pcpu,pmem,args")
      (tramp-process-attributes-ps-format
       (pid . number)
       (euid . number)
       (user . string)
       (egid . number)
       (group . string)
       (comm . 52)
       (state . string)
       (ppid . number)
       (pgrp . number)
       (sess . number)
       (ttname . string)
       (tpgid . number)
       (minflt . number)
       (majflt . number)
       (time . tramp-ps-time)
       (pri . number)
       (nice . number)
       (vsize . number)
       (rss . number)
       (etime . number)
       (pcpu . number)
       (pmem . number)
       (args)))
     (tramp-connection-local-default-shell-profile
      (shell-file-name . "/bin/sh")
      (shell-command-switch . "-c"))
     (tramp-connection-local-default-system-profile
      (path-separator . ":")
      (null-device . "/dev/null"))))
 '(custom-safe-themes
   '("fa2b58bb98b62c3b8cf3b6f02f058ef7827a8e497125de0254f56e373abee088" "bffa9739ce0752a37d9b1eee78fc00ba159748f50dc328af4be661484848e476" "dad40020beea412623b04507a4c185079bff4dcea20a93d8f8451acb6afc8358" "a0415d8fc6aeec455376f0cbcc1bee5f8c408295d1c2b9a1336db6947b89dd98" "d600c677f1777c1e4bfb066529b5b73c0179d0499dd4ffa3f599a0fb0cfbd501" default))
 '(ispell-program-name "hunspell")
 '(lsp-keymap-prefix "M-#")
 '(modus-themes-bold-constructs t)
 '(modus-themes-diffs 'desaturated)
 '(modus-themes-fringes 'subtle)
 '(modus-themes-headings
   '((1 background overline rainbow)
     (2 background rainbow)
     (3 no-bold rainbow)
     (t no-bold)))
 '(modus-themes-italic-constructs t)
 '(modus-themes-mode-line '(nil accented))
 '(modus-themes-org-agenda '((header-block variable-pitch) (header-date bold-today)))
 '(modus-themes-org-blocks nil)
 '(modus-themes-paren-match '(bold intense))
 '(modus-themes-prompts '(intense bold))
 '(modus-themes-region '(bg-only))
 '(modus-themes-scale-headings t)
 '(modus-themes-subtle-line-numbers t)
 '(modus-themes-syntax '(yellow-comments green-strings))
 '(modus-themes-tabs-accented t)
 '(modus-themes-variable-pitch-headings t)
 '(modus-themes-variable-pitch-ui t)
 '(package-selected-packages
   '(emacsql magit treemacs evil forge closql js2-mode helm helm-core ws-butler flycheck-rust pyenv-mode emmet-mode aggressive-indent restart-emacs lorem-ipsum conda multi-line rubocopfmt spacemacs-purpose-popwin all-the-icons-ibuffer spacemacs-whitespace-cleanup nix-mode esh-help spaceline-all-the-icons which-key column-enforce-mode pangu-spacing hide-comnt command-log-mode toml-mode compleseus-spacemacs-help tagedit flycheck-rtags emoji-cheat-sheet-plus ivy-bibtex robe undo-tree flycheck-bashate git-gutter-fringe hyperbole rime google-translate symon subed org-pomodoro insert-shebang pip-requirements keycast auctex flyspell-popup vim-powerline journalctl-mode json-mode indent-guide quickrun flycheck-pos-tip emacs-everywhere cmake-mode eval-sexp-fu livid-mode aweshell magic-latex-buffer rvm nov consult-projectile poetry rubocop pyim-basedict elisp-slime-nav zoom-window evil-lisp-state web-beautify sql-indent org-fc mmm-mode markdown-toc ruby-refactor paradox pyim info+ seeing-is-believing highlight-numbers systemd help-fns+ org-rich-yank popwin disaster watch-other-window uuidgen eyebrowse emamux ibuffer-projectile nixos-options diminish org-mime chinese-conv pydoc org-auto-tangle symbol-overlay eshell-z rake org-wild-notifier json-reformat math-symbol-lists tree-sitter-langs popon engine-mode cython-mode auto-dictionary font-lock+ rainbow-delimiters holy-mode google-c-style drag-stuff lsp-bridge org-appear consult-yasnippet sphinx-doc gitignore-templates smeargle org-ref typo-suggest dired-quick-sort expand-region cargo evil-cleverparens ruby-test-mode highlight-parentheses devdocs npm-mode flx-ido git-link evil-evilified-state git-modes unkillable-scratch scss-mode org-transclusion ivy-purpose org-fragtog org-contrib py-isort yapfify define-word multi-vterm browse-at-remote nameless hybrid-mode highlight-indentation rspec-mode org-superstar nose link-hint rbenv ace-link nodejs-repl live-py-mode eshell-prompt-extras consult-dir js2-refactor minitest toc-org bundler fancy-battery web-mode org-roam-bibtex auto-compile yaml-mode centered-cursor-mode wgrep shell-pop macrostep dumb-jump org-web-tools clean-aindent-mode flyspell-correct-popup blacken org-vcard ebib ron-mode org-present inspector treemacs-icons-dired cpp-auto-include demo-it pdf-view-restore pylookup ruby-tools find-by-pinyin-dired jupyter auto-highlight-symbol treemacs-persp djvu csv-mode sqlup-mode cmake-ide anaconda-mode gif-screencast treemacs-magit password-generator chruby ob-tmux golden-ratio org-roam-ui org-noter-pdftools hl-todo impatient-mode gendoxy orderless importmagic unfill org-download magit-gitflow fancy-narrow dotenv-mode mwim slim-mode org-tree-slide multi-term graphviz-dot-mode shfmt org-cliplink xterm-color marginalia eaf youdao-dictionary racer fish-mode open-junk-file winum acm-terminal gh-md org-contacts editorconfig ace-pinyin hungry-delete elisp-def git-messenger js-doc yasnippet-snippets cdlatex consult-org-roam counsel-css dockerfile-mode space-doc counsel-projectile sass-mode pug-mode ruby-hash-syntax orgit-forge flycheck-ycmd cliphist ivy-rtags prettier-js flycheck-package popweb vertico pytest embark-consult all-the-icons-dired emr overseer volatile-highlights plantuml-mode emojify code-cells json-navigator flycheck-elsa pippel string-edit-at-point term-cursor docker gnuplot adoc-mode ox-hugo terminal-here treemacs-projectile ox-epub pipenv git-timemachine writeroom-mode))
 '(plantuml-indent-level 4)
 '(safe-local-variable-values
   '((conda-project-env-path . "/home/xin/.conda/envs/gallery-dl")
     (javascript-backend . tide)
     (javascript-backend . tern)
     (javascript-backend . lsp)))
 '(spacemacs-theme-comment-bg nil)
 '(spacemacs-theme-org-agenda-height t)
 '(time-stamp-format " <%Y-%02m-%02d %3a %02H:%02M by %u on %s>")
 '(time-stamp-time-zone t)
 '(undo-tree-auto-save-history nil)
 '(valign-fancy-bar t)
 '(writeroom-width 0.65)
 '(xref-search-program 'ripgrep))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(cursor ((t (:background "lime green"))))
 '(highlight-indentation-current-column-face ((t (:background "gold"))))
 '(highlight-indentation-face ((t (:background "dim gray"))))
 '(highlight-parentheses-highlight ((nil (:weight ultra-bold))) t)
 '(keycast-command ((t (:inherit bold :extend t :foreground "#34cfff" :underline t :height 1.3 :family "monospace"))))
 '(keycast-key ((t (:inherit bold :background "#34cfff" :foreground "black" :box (:line-width (2 . 2) :color "spring green" :style pressed-button) :height 1.6 :family "monospace")))))
