(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   '("aec7b55f2a13307a55517fdf08438863d694550565dee23181d2ebd973ebd6b8" "02f57ef0a20b7f61adce51445b68b2a7e832648ce2e7efb19d217b6454c1b644" "adaf421037f4ae6725aa9f5654a2ed49e2cd2765f71e19a7d26a454491b486eb" "443e2c3c4dd44510f0ea8247b438e834188dc1c6fb80785d83ad3628eadf9294" "f74e8d46790f3e07fbb4a2c5dafe2ade0d8f5abc9c203cd1c29c7d5110a85230" "bffa9739ce0752a37d9b1eee78fc00ba159748f50dc328af4be661484848e476" default))
 '(package-selected-packages
   '(multi-line treemacs evil which-key zoom-window zenburn-theme youdao-dictionary yasnippet-snippets xterm-color ws-butler writeroom-mode winum window-purpose wgrep web-beautify watch-other-window volatile-highlights vim-powerline vertico-posframe verb uuidgen unkillable-scratch unfill undo-tree treesit-auto treemacs-projectile treemacs-persp treemacs-magit treemacs-icons-dired toc-org terminal-here term-cursor symon symbol-overlay subed string-edit-at-point spacemacs-whitespace-cleanup spacemacs-purpose-popwin spaceline space-doc smeargle smartparens shut-up shell-pop sdcv screenshot rime restart-emacs rainbow-delimiters quickrun prettier-js popwin popon plantuml-mode pinyinlib persistent-scratch pdf-view-restore pcre2el password-generator paradox pangu-spacing ox-epub overseer orgit-forge org-wild-notifier org-web-tools org-vcard org-tree-slide org-transclusion org-roam-ui org-roam-bibtex org-ref org-present org-pomodoro org-noter-pdftools org-modern org-mime org-fragtog org-fc org-emms org-download org-contrib org-contacts org-cliplink org-auto-tangle orderless open-junk-file ob-tmux nov nameless mwim multiple-cursors multi-vterm multi-term math-symbol-lists marginalia magit-gitflow magic-latex-buffer macrostep lsp-bridge lorem-ipsum link-hint keycast jupyter json-reformat json-navigator json-mode inspector info+ indent-guide ibuffer-projectile hyperbole hybrid-mode hungry-delete holy-mode hl-todo highlight-parentheses highlight-numbers highlight-indentation hide-comnt help-fns+ goto-chg google-translate google-c-style golden-ratio gnuplot gitignore-templates git-timemachine git-modes git-messenger git-link gif-screencast gendoxy flyspell-popup flyspell-correct-popup flycheck-ycmd flycheck-rtags flycheck-package flycheck-elsa flx-ido fanyi fancy-narrow fancy-battery eyebrowse expand-region evil-evilified-state eval-sexp-fu eshell-z eshell-prompt-extras esh-help engine-mode emr emms-info-mediainfo embark-consult emamux emacs-everywhere elisp-slime-nav elisp-def editorconfig ebib eaf dumb-jump drag-stuff dotenv-mode doom-themes dockerfile-mode docker djvu disaster dired-quick-sort diminish devdocs demo-it define-word cpp-auto-include consult-yasnippet consult-projectile consult-org-roam consult-dir conda compleseus-spacemacs-help command-log-mode column-enforce-mode color-theme-sanityinc-tomorrow cmake-mode cmake-ide clean-aindent-mode cfrs centered-cursor-mode cdlatex bind-map bilibili aweshell auto-highlight-symbol auto-dictionary auto-compile auctex-latexmk all-the-icons-ibuffer all-the-icons-dired aggressive-indent acm-terminal ace-window ace-link)))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
